In [1]:
from selenium import webdriver
import pandas as pd

In [4]:
driver = driver = webdriver.Chrome('D:\chromedriver_win32\chromedriver.exe')


driver.get('https://pokemondb.net/pokedex/all')
driver.maximize_window()

In [5]:
# Policy Policy
button = driver.find_element_by_class_name('gdpr-accept')
#button=driver.find_element_by_class_name('btn-primary')(three different classes are here try to choose anyone according to sir)
#button = driver.find_element_by_class_name('btn')
try:
    button.click()
except:
    pass

In [6]:
pokemon_name = driver.find_elements_by_xpath('//tbody/tr/td[2]')

In [7]:
pokemon_type = driver.find_elements_by_xpath('//tbody/tr/td[3]')

In [8]:
pokemon_total = driver.find_elements_by_xpath('//tbody/tr/td[4]')

In [9]:
pokemon_hp = driver.find_elements_by_xpath('//tbody/tr/td[5]')

In [10]:
pokemon_attack = driver.find_elements_by_xpath('//tbody/tr/td[6]')

In [11]:
pokemon_defense = driver.find_elements_by_xpath('//tbody/tr/td[7]')

In [12]:
pokemon_sp_attack = driver.find_elements_by_xpath('//tbody/tr/td[8]')

In [14]:
pokemon_sp_defense = driver.find_elements_by_xpath('//tbody/tr/td[9]')

In [15]:
pokemon_speed = driver.find_elements_by_xpath('//tbody/tr/td[10]')

In [16]:
pokemon_results = []

In [17]:
for i in range(len(pokemon_name)):
    pokemon_dictionary={'Name':pokemon_name[i].text,
                       'Type': pokemon_type[i].text,
                       'Total':pokemon_total[i].text,
                       'HP': pokemon_hp[i].text,
                       'Attack':pokemon_attack[i].text,
                       'Defense': pokemon_defense[i].text,
                       'Sp.Attack': pokemon_sp_attack[i].text,
                       'Sp.Defense': pokemon_sp_defense[i].text,
                       'Speed':pokemon_speed[i].text}
    
    pokemon_results.append(pokemon_dictionary)

In [18]:
dataframe_pokemon = pd.DataFrame(pokemon_results)

In [19]:
dataframe_pokemon.head(5)

,Name,Type,Total,HP,Attack,Defense,Sp.Attack,Sp.Defense,Speed
0,Bulbasaur,GRASS\nPOISON,318,45,49,49,65,65,45
1,Ivysaur,GRASS\nPOISON,405,60,62,63,80,80,60
2,Venusaur,GRASS\nPOISON,525,80,82,83,100,100,80
3,Venusaur\nMega Venusaur,GRASS\nPOISON,625,80,100,123,122,120,80
4,Charmander,FIRE,309,39,52,43,60,50,65

In [20]:
#replace '\n' with '/'
dataframe_pokemon['Name'] = dataframe_pokemon['Name'].apply(lambda x: x.replace ('\n', '/'))

In [21]:
#replace '\n' with a comma
dataframe_pokemon['Type'] = dataframe_pokemon['Type'].apply(lambda x: x.replace ('\n', ','))

In [22]:
# updated dataframe
dataframe_pokemon.head(20)

,Name,Type,Total,HP,Attack,Defense,Sp.Attack,Sp.Defense,Speed
0,Bulbasaur,"GRASS,POISON",318,45,49,49,65,65,45
1,Ivysaur,"GRASS,POISON",405,60,62,63,80,80,60
2,Venusaur,"GRASS,POISON",525,80,82,83,100,100,80
3,Venusaur/Mega Venusaur,"GRASS,POISON",625,80,100,123,122,120,80
4,Charmander,FIRE,309,39,52,43,60,50,65
5,Charmeleon,FIRE,405,58,64,58,80,65,80
6,Charizard,"FIRE,FLYING",534,78,84,78,109,85,100
7,Charizard/Mega Charizard X,"FIRE,DRAGON",634,78,130,111,130,85,100
8,Charizard/Mega Charizard Y,"FIRE,FLYING",634,78,104,78,159,115,100
9,Squirtle,WATER,314,44,48,65,50,64,43
10,Wartortle,WATER,405,59,63,80,65,80,58
11,Blastoise,WATER,530,79,83,100,85,105,78
12,Blastoise/Mega Blastoise,WATER,630,79,103,120,135,115,78
13,Caterpie,BUG,195,45,30,35,20,20,45
14,Metapod,BUG,205,50,20,55,25,25,30
15,Butterfree,"BUG,FLYING",395,60,45,50,90,80,70
16,Weedle,"BUG,POISON",195,40,35,30,20,20,50
17,Kakuna,"BUG,POISON",205,45,25,50,25,25,35
18,Beedrill,"BUG,POISON",395,65,90,40,45,80,75
19,Beedrill/Mega Beedrill,"BUG,POISON",495,65,150,40,15,80,145

In [23]:
dataframe_pokemon.to_excel('pokemon_database_cleaned.xlsx', index=False)